//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Artwork {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Artwork() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Artwork", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is Rework required?.
        /// </summary>
        internal static string Error_ADBLevel1ReworkRequired {
            get {
                return ResourceManager.GetString("Error_ADBLevel1ReworkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Type is required..
        /// </summary>
        internal static string Error_ArtworkType {
            get {
                return ResourceManager.GetString("Error_ArtworkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Code is required (Max allow 15 digits)..
        /// </summary>
        internal static string Error_BarCode {
            get {
                return ResourceManager.GetString("Error_BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit is required..
        /// </summary>
        internal static string Error_BusinessUnit {
            get {
                return ResourceManager.GetString("Error_BusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic/Imported is required..
        /// </summary>
        internal static string Error_DomesticOrImported {
            get {
                return ResourceManager.GetString("Error_DomesticOrImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Photo is required.
        /// </summary>
        internal static string Error_FNLABSQApprover {
            get {
                return ResourceManager.GetString("Error_FNLABSQApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QAP Attachment is required..
        /// </summary>
        internal static string Error_FNLQAPAttachment {
            get {
                return ResourceManager.GetString("Error_FNLQAPAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Photo is required..
        /// </summary>
        internal static string Error_FNLSamplePhoto {
            get {
                return ResourceManager.GetString("Error_FNLSamplePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Specification Attachment is required..
        /// </summary>
        internal static string Error_FNLTechnicalSpecificationAttachment {
            get {
                return ResourceManager.GetString("Error_FNLTechnicalSpecificationAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code is required (Max allow 255 char)..
        /// </summary>
        internal static string Error_ItemCode {
            get {
                return ResourceManager.GetString("Error_ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is Rework required?.
        /// </summary>
        internal static string Error_MarketingLevel1ReworkRequired {
            get {
                return ResourceManager.GetString("Error_MarketingLevel1ReworkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Carton Dimension  is required (Max allow 15 digits)..
        /// </summary>
        internal static string Error_MasterCartondimension {
            get {
                return ResourceManager.GetString("Error_MasterCartondimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Carton Dimension Height is required (Max allow 15 digits)..
        /// </summary>
        internal static string Error_MasterCartondimensionH {
            get {
                return ResourceManager.GetString("Error_MasterCartondimensionH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Carton Dimension Lenght is required (Max allow 15 digits)..
        /// </summary>
        internal static string Error_MasterCartondimensionL {
            get {
                return ResourceManager.GetString("Error_MasterCartondimensionL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Carton Dimension Width is required (Max allow 15 digits)..
        /// </summary>
        internal static string Error_MasterCartondimensionW {
            get {
                return ResourceManager.GetString("Error_MasterCartondimensionW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Name is required (Max allow 255 char)..
        /// </summary>
        internal static string Error_ModelName {
            get {
                return ResourceManager.GetString("Error_ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRP (In Rs.) is required (Max allow 15 digits)..
        /// </summary>
        internal static string Error_MRP {
            get {
                return ResourceManager.GetString("Error_MRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Carton in Master is required (Max allow 15 digits)..
        /// </summary>
        internal static string Error_NoofCartoninMaster {
            get {
                return ResourceManager.GetString("Error_NoofCartoninMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is required..
        /// </summary>
        internal static string Error_Product {
            get {
                return ResourceManager.GetString("Error_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category is required..
        /// </summary>
        internal static string Error_ProductCategory {
            get {
                return ResourceManager.GetString("Error_ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Feature is required (Max allow 1000 char)..
        /// </summary>
        internal static string Error_ProductFeature {
            get {
                return ResourceManager.GetString("Error_ProductFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is Rework required?.
        /// </summary>
        internal static string Error_QALevel1ReworkRequired {
            get {
                return ResourceManager.GetString("Error_QALevel1ReworkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is Rework required?.
        /// </summary>
        internal static string Error_SCMLevel1ReworkRequired {
            get {
                return ResourceManager.GetString("Error_SCMLevel1ReworkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Type is required..
        /// </summary>
        internal static string Error_StrArtworkTypeList {
            get {
                return ResourceManager.GetString("Error_StrArtworkTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Code is required (4 digit only)..
        /// </summary>
        internal static string Error_SupplierCode {
            get {
                return ResourceManager.GetString("Error_SupplierCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Carton Dimension is required (Max allow 15 digits)..
        /// </summary>
        internal static string Error_UnitCartonDimension {
            get {
                return ResourceManager.GetString("Error_UnitCartonDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Carton Dimension Height is required (Max allow 15 digits)..
        /// </summary>
        internal static string Error_UnitCartonDimensionH {
            get {
                return ResourceManager.GetString("Error_UnitCartonDimensionH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Carton Dimension Length is required (Max allow 15 digits)..
        /// </summary>
        internal static string Error_UnitCartonDimensionL {
            get {
                return ResourceManager.GetString("Error_UnitCartonDimensionL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Carton Dimension Width is required (Max allow 15 digits)..
        /// </summary>
        internal static string Error_UnitCartonDimensionW {
            get {
                return ResourceManager.GetString("Error_UnitCartonDimensionW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Address is required (Max allow 1000 char)..
        /// </summary>
        internal static string Error_VendorAddress {
            get {
                return ResourceManager.GetString("Error_VendorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Code is required (Max allow 255 char)..
        /// </summary>
        internal static string Error_VendorCode {
            get {
                return ResourceManager.GetString("Error_VendorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty is required (Max allow 15 digits)..
        /// </summary>
        internal static string Error_Warranty {
            get {
                return ResourceManager.GetString("Error_Warranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data in Artwork Type.
        /// </summary>
        internal static string Grid_Text_NoArtworkType {
            get {
                return ResourceManager.GetString("Grid_Text_NoArtworkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Applicable (check if not applicable).
        /// </summary>
        internal static string Grid_Title_Applicable {
            get {
                return ResourceManager.GetString("Grid_Title_Applicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Type.
        /// </summary>
        internal static string Grid_Title_ArtworkType {
            get {
                return ResourceManager.GetString("Grid_Title_ArtworkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string Grid_Title_FileName {
            get {
                return ResourceManager.GetString("Grid_Title_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Type:.
        /// </summary>
        internal static string Label_ArtworkType {
            get {
                return ResourceManager.GetString("Label_ArtworkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Code:.
        /// </summary>
        internal static string Label_BarCode {
            get {
                return ResourceManager.GetString("Label_BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit:.
        /// </summary>
        internal static string Label_BusinessUnit {
            get {
                return ResourceManager.GetString("Label_BusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Description / Comment :.
        /// </summary>
        internal static string Label_ChangeDescription {
            get {
                return ResourceManager.GetString("Label_ChangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        internal static string Label_Color {
            get {
                return ResourceManager.GetString("Label_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments / Remarks:.
        /// </summary>
        internal static string Label_Comments {
            get {
                return ResourceManager.GetString("Label_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic / Imported:.
        /// </summary>
        internal static string Label_DomesticOrImported {
            get {
                return ResourceManager.GetString("Label_DomesticOrImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments:.
        /// </summary>
        internal static string Label_FileNameList {
            get {
                return ResourceManager.GetString("Label_FileNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Photo:.
        /// </summary>
        internal static string Label_FNLABSQApprover {
            get {
                return ResourceManager.GetString("Label_FNLABSQApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Photos:.
        /// </summary>
        internal static string Label_FNLADBLevel1Attachment {
            get {
                return ResourceManager.GetString("Label_FNLADBLevel1Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Photos:.
        /// </summary>
        internal static string Label_FNLADBLevel2Attachment {
            get {
                return ResourceManager.GetString("Label_FNLADBLevel2Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Photo:.
        /// </summary>
        internal static string Label_FNLMarketingLevel1Attachment {
            get {
                return ResourceManager.GetString("Label_FNLMarketingLevel1Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Photo:.
        /// </summary>
        internal static string Label_FNLMarketingLevel2Attachment {
            get {
                return ResourceManager.GetString("Label_FNLMarketingLevel2Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Photo:.
        /// </summary>
        internal static string Label_FNLQALevel1Attachment {
            get {
                return ResourceManager.GetString("Label_FNLQALevel1Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Photo:.
        /// </summary>
        internal static string Label_FNLQALevel2Attachment {
            get {
                return ResourceManager.GetString("Label_FNLQALevel2Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QAP:.
        /// </summary>
        internal static string Label_FNLQAPAttachment {
            get {
                return ResourceManager.GetString("Label_FNLQAPAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Photo:.
        /// </summary>
        internal static string Label_FNLSamplePhoto {
            get {
                return ResourceManager.GetString("Label_FNLSamplePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Photos:.
        /// </summary>
        internal static string Label_FNLSCMLevel1Attachment {
            get {
                return ResourceManager.GetString("Label_FNLSCMLevel1Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Photos:.
        /// </summary>
        internal static string Label_FNLSCMLevel2Attachment {
            get {
                return ResourceManager.GetString("Label_FNLSCMLevel2Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Specifications:.
        /// </summary>
        internal static string Label_FNLTechnicalSpecificationAttachment {
            get {
                return ResourceManager.GetString("Label_FNLTechnicalSpecificationAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Weight (In Kgs):.
        /// </summary>
        internal static string Label_GrossWeight {
            get {
                return ResourceManager.GetString("Label_GrossWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code:.
        /// </summary>
        internal static string Label_ItemCode {
            get {
                return ResourceManager.GetString("Label_ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Carton Dimension:.
        /// </summary>
        internal static string Label_MasterCartondimension {
            get {
                return ResourceManager.GetString("Label_MasterCartondimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Carton Dimension (in mm):.
        /// </summary>
        internal static string Label_MasterCartondimensionH {
            get {
                return ResourceManager.GetString("Label_MasterCartondimensionH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Carton Dimension (in mm):.
        /// </summary>
        internal static string Label_MasterCartondimensionL {
            get {
                return ResourceManager.GetString("Label_MasterCartondimensionL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Carton Dimension (in mm):.
        /// </summary>
        internal static string Label_MasterCartondimensionW {
            get {
                return ResourceManager.GetString("Label_MasterCartondimensionW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Name:.
        /// </summary>
        internal static string Label_ModelName {
            get {
                return ResourceManager.GetString("Label_ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRP (In Rs.):.
        /// </summary>
        internal static string Label_MRP {
            get {
                return ResourceManager.GetString("Label_MRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Weight (In Kgs):.
        /// </summary>
        internal static string Label_NetWeight {
            get {
                return ResourceManager.GetString("Label_NetWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Carton in Master:.
        /// </summary>
        internal static string Label_NoofCartoninMaster {
            get {
                return ResourceManager.GetString("Label_NoofCartoninMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Artwork Created Date:.
        /// </summary>
        internal static string Label_OldArtworkCreatedDate {
            get {
                return ResourceManager.GetString("Label_OldArtworkCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Artwork Rejected Comment:.
        /// </summary>
        internal static string Label_OldArtworkRejectedComment {
            get {
                return ResourceManager.GetString("Label_OldArtworkRejectedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Artwork Rejected Date:.
        /// </summary>
        internal static string Label_OldArtworkRejectedDate {
            get {
                return ResourceManager.GetString("Label_OldArtworkRejectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Reference No:.
        /// </summary>
        internal static string Label_OldReferenceNo {
            get {
                return ResourceManager.GetString("Label_OldReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power (In Watt):.
        /// </summary>
        internal static string Label_Power {
            get {
                return ResourceManager.GetString("Label_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product:.
        /// </summary>
        internal static string Label_Product {
            get {
                return ResourceManager.GetString("Label_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category:.
        /// </summary>
        internal static string Label_ProductCategory {
            get {
                return ResourceManager.GetString("Label_ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Feature:.
        /// </summary>
        internal static string Label_ProductFeature {
            get {
                return ResourceManager.GetString("Label_ProductFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name:.
        /// </summary>
        internal static string Label_ProductName {
            get {
                return ResourceManager.GetString("Label_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed By:.
        /// </summary>
        internal static string Label_ProposedBy {
            get {
                return ResourceManager.GetString("Label_ProposedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality User:.
        /// </summary>
        internal static string Label_QAUser {
            get {
                return ResourceManager.GetString("Label_QAUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No:.
        /// </summary>
        internal static string Label_ReferenceNo {
            get {
                return ResourceManager.GetString("Label_ReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date:.
        /// </summary>
        internal static string Label_RequestDate {
            get {
                return ResourceManager.GetString("Label_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department:.
        /// </summary>
        internal static string Label_RequesterBusinessUnit {
            get {
                return ResourceManager.GetString("Label_RequesterBusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester&apos;s Domestic/Imported:.
        /// </summary>
        internal static string Label_RequesterDomesticOrImported {
            get {
                return ResourceManager.GetString("Label_RequesterDomesticOrImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Rework recommended?:.
        /// </summary>
        internal static string Label_ReworkRequired {
            get {
                return ResourceManager.GetString("Label_ReworkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Carton Dimension:.
        /// </summary>
        internal static string Label_UnitCartonDimension {
            get {
                return ResourceManager.GetString("Label_UnitCartonDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Carton Dimension (in mm):.
        /// </summary>
        internal static string Label_UnitCartonDimensionH {
            get {
                return ResourceManager.GetString("Label_UnitCartonDimensionH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Carton Dimension (in mm):.
        /// </summary>
        internal static string Label_UnitCartonDimensionL {
            get {
                return ResourceManager.GetString("Label_UnitCartonDimensionL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Carton Dimension (in mm):.
        /// </summary>
        internal static string Label_UnitCartonDimensionW {
            get {
                return ResourceManager.GetString("Label_UnitCartonDimensionW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Address:.
        /// </summary>
        internal static string Label_VendorAddress {
            get {
                return ResourceManager.GetString("Label_VendorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Code:.
        /// </summary>
        internal static string Label_VendorCode {
            get {
                return ResourceManager.GetString("Label_VendorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage (In Volts):.
        /// </summary>
        internal static string Label_Voltage {
            get {
                return ResourceManager.GetString("Label_Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty (In Years):.
        /// </summary>
        internal static string Label_Warranty {
            get {
                return ResourceManager.GetString("Label_Warranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Status.
        /// </summary>
        internal static string Label_WorkflowStatus {
            get {
                return ResourceManager.GetString("Label_WorkflowStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABSQ Approver Section.
        /// </summary>
        internal static string Section_Title_ABSQApproverSection {
            get {
                return ResourceManager.GetString("Section_Title_ABSQApproverSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABSQ Team Section.
        /// </summary>
        internal static string Section_Title_ABSQTeamSection {
            get {
                return ResourceManager.GetString("Section_Title_ABSQTeamSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB Level 1 Section.
        /// </summary>
        internal static string Section_Title_ADBLevel1Section {
            get {
                return ResourceManager.GetString("Section_Title_ADBLevel1Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB Level 2 Section.
        /// </summary>
        internal static string Section_Title_ADBLevel2Section {
            get {
                return ResourceManager.GetString("Section_Title_ADBLevel2Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Marketing Level 1 Section.
        /// </summary>
        internal static string Section_Title_MarketingLevel1Section {
            get {
                return ResourceManager.GetString("Section_Title_MarketingLevel1Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Marketing Level 2 Section.
        /// </summary>
        internal static string Section_Title_MarketingLevel2Section {
            get {
                return ResourceManager.GetString("Section_Title_MarketingLevel2Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BU Approver Section.
        /// </summary>
        internal static string Section_Title_NewArtworkBUHeadSection {
            get {
                return ResourceManager.GetString("Section_Title_NewArtworkBUHeadSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Detail Section.
        /// </summary>
        internal static string Section_Title_NewArtworkDetailDocumentSection {
            get {
                return ResourceManager.GetString("Section_Title_NewArtworkDetailDocumentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        internal static string Section_Title_NewArtworkDisclaimerSection {
            get {
                return ResourceManager.GetString("Section_Title_NewArtworkDisclaimerSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA Level 1 Section.
        /// </summary>
        internal static string Section_Title_QALevel1Section {
            get {
                return ResourceManager.GetString("Section_Title_QALevel1Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA Level 2 Section.
        /// </summary>
        internal static string Section_Title_QALevel2Section {
            get {
                return ResourceManager.GetString("Section_Title_QALevel2Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCM Level 1 Section.
        /// </summary>
        internal static string Section_Title_SCMLevel1Section {
            get {
                return ResourceManager.GetString("Section_Title_SCMLevel1Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCM Level 2 Section.
        /// </summary>
        internal static string Section_Title_SCMLevel2Section {
            get {
                return ResourceManager.GetString("Section_Title_SCMLevel2Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Artwork.
        /// </summary>
        internal static string Section_Title_ViewArtworkDetailDocumentSection {
            get {
                return ResourceManager.GetString("Section_Title_ViewArtworkDetailDocumentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin user can not delete document which is uploaded by ABSQ team..
        /// </summary>
        internal static string Text_AdminUserdelete {
            get {
                return ResourceManager.GetString("Text_AdminUserdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork  is approved successfully.
        /// </summary>
        internal static string Text_ApproveSuccess {
            get {
                return ResourceManager.GetString("Text_ApproveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For downloading artworks type attachments, please .
        /// </summary>
        internal static string Text_ArtworkTypeNote {
            get {
                return ResourceManager.GetString("Text_ArtworkTypeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork is completed successfully.
        /// </summary>
        internal static string Text_CompletedSuccess {
            get {
                return ResourceManager.GetString("Text_CompletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork draft request is deleted successfully..
        /// </summary>
        internal static string Text_DeleteSuccess {
            get {
                return ResourceManager.GetString("Text_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code already exist..
        /// </summary>
        internal static string Text_DuplicateItemCode {
            get {
                return ResourceManager.GetString("Text_DuplicateItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork has been hold successfully..
        /// </summary>
        internal static string Text_HoldSuccess {
            get {
                return ResourceManager.GetString("Text_HoldSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork request for this Item code is in progress..
        /// </summary>
        internal static string Text_ItemCodeLocked {
            get {
                return ResourceManager.GetString("Text_ItemCodeLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;bull; Once Existing Artwork Workflow in progress with any item code, then other existing artwork flow can not start with the same item code. &lt;br&gt;
        ///&amp;bull; Once Existing Artwork Workflow is completed with any item code, then other existing artwork flow can not start with the same item code before 120 days.&lt;br&gt;
        ///&amp;bull; Once Existing Artwork is rejected with any item code , only ABS admin can retrive it. But another requestor user can create existing artwork using same item code after 120 days..
        /// </summary>
        internal static string Text_Note {
            get {
                return ResourceManager.GetString("Text_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork is rejected successfully.
        /// </summary>
        internal static string Text_RejectedSuccess {
            get {
                return ResourceManager.GetString("Text_RejectedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork has been resumed..
        /// </summary>
        internal static string Text_ResumeSuccess {
            get {
                return ResourceManager.GetString("Text_ResumeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork is sent back for rework.
        /// </summary>
        internal static string Text_ReworkSuccess {
            get {
                return ResourceManager.GetString("Text_ReworkSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork file save as draft successfully..
        /// </summary>
        internal static string Text_SaveAsDraftSuccess {
            get {
                return ResourceManager.GetString("Text_SaveAsDraftSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork save as draft successfully.
        /// </summary>
        internal static string Text_SaveDraftSuccess {
            get {
                return ResourceManager.GetString("Text_SaveDraftSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork saved successfully.
        /// </summary>
        internal static string Text_SaveSuccess {
            get {
                return ResourceManager.GetString("Text_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Sent Fail..
        /// </summary>
        internal static string Text_SentEmailtoABSQFail {
            get {
                return ResourceManager.GetString("Text_SentEmailtoABSQFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request has been email to ABSQ Team for Upload Artwork Type Files.
        /// </summary>
        internal static string Text_SentEmailtoABSQSuccess {
            get {
                return ResourceManager.GetString("Text_SentEmailtoABSQSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork is submitted successfully.
        /// </summary>
        internal static string Text_Success {
            get {
                return ResourceManager.GetString("Text_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork file uploaded successfully..
        /// </summary>
        internal static string Text_UpdateSuccess {
            get {
                return ResourceManager.GetString("Text_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABSQ User will Upload Artwork Type files..
        /// </summary>
        internal static string Text_ViewArtworkNote {
            get {
                return ResourceManager.GetString("Text_ViewArtworkNote", resourceCulture);
            }
        }
    }
}
